set guioptions-=m "No menu
set guioptions-=T "No toolbar
set mouse=""

" hack to vanish scrollbars
set guioptions+=lrb
set guioptions-=lrb

colorscheme solarized 
" set background=dark
" colorscheme solarized
" Ctrl-S for saving
imap <c-s> <Esc><c-s>

" Set initial window size
set lines=50 columns=120

