" Load pathogen.
" Needed on some linux distros.
" see http://www.adamlowe.me/2009/12/vim-destroys-all-other-rails-editors.html
set nocompatible
filetype off
filetype plugin indent off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'Townk/vim-autoclose'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'godlygeek/tabular'
Plugin 'majutsushi/tagbar'
Plugin 'tomtom/tcomment_vim'
Plugin 'rking/ag.vim'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'gregsexton/gitv.git'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'tpope/vim-markdown.git'
Plugin 'tpope/vim-rails.git'
Plugin 'vim-ruby/vim-ruby.git'
Plugin 'tpope/vim-surround.git'
Plugin 'kana/vim-textobj-user.git'
Plugin 'nelstrom/vim-textobj-rubyblock.git'
Plugin 'd11wtq/ctrlp_bdelete.vim'
Plugin 'benmills/vimux'
Plugin 'jgdavey/vim-turbux'
Plugin 'justinmk/vim-gtfo'
Plugin 'epeli/slimux'
Plugin 'pangloss/vim-javascript'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'vim-scripts/dbext.vim'
call vundle#end()

filetype plugin indent on

set background=dark
set colorcolumn=100

" set t_Co=256
" let g:solarized_termcolors=256
" colorscheme solarized

colorscheme lucius
LuciusBlack


syntax on
" set foldmethod=syntax

" enable matchit.vim for rubytext-block
runtime macros/matchit.vim

set nowrap "disable wrapping

set hidden "you can change buffers without saving
set expandtab
set tabstop=2
set shiftwidth=2
set bs=2
set number "show numbers
set showcmd "show partial command you are typing
set smarttab
set autoindent

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" put all vim's temporary file out of current dir
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" set the leader key
let mapleader = ","

" Keymaps
nnoremap <c-c> <ESC> " alternative ESCAPE
inoremap jj <ESC>
nmap <F3> :cn<CR> " find next occurance after vimgrep
nmap <F4> :cp<CR> " find previous occurance after vimgrep

" remap Turbux keybindings
let g:no_turbux_mappings = 1
map <leader>x <Plug>SendTestToTmux
map <leader>X <Plug>SendFocusedTestToTmux

" Turbux should use drb by default
let g:turbux_command_prefix = 'bundle exec'
let g:turbux_command_cucumber  = 'cucumber --drb'
let g:turbux_command_rspec     = 'rspec -f d'
let g:turbux_command_test_unit = 'ruby -Itest'

 "change default cursor keys to work on visual not actual lines
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

if has("gui_running")
  " If the current buffer has never been saved, it will have no name,
  " call the file browser to save it, otherwise just save it.
  :map <silent> <C-S> :if expand("%") == ""<CR>:browse confirm w<CR>:else<CR>:confirm w<CR>:endif<CR>
endif

" Toggle invisible characters
nmap <silent> ,l :set list!<CR>

" Close all buffers except current one (via BufOnly.vim)
nmap <silent> ,w :BufOnly<CR>

" CtrlP in open buffer mode
map <silent> ,t :CtrlPBuffer<CR>
map <silent> ,m :CtrlPMRU<CR>

" Preview Markdown files
map <leader>P :Mm<CR>

" Toggle the NERDTree
map <silent> ,e :NERDTreeToggle<CR>

" Send to REPL
map <Leader>s :SlimuxREPLSendLine<CR>
vmap <Leader>s :SlimuxREPLSendSelection<CR>

" Status Line
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]

" statusline support for syntactic plugin
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" Statusline always visible
set laststatus=2

" Close NERDTree when opening a file
let g:NERDTreeQuitOnOpen = 1

" Size of window
let g:NERDTreeWinSize = 40

" Enable syntastic syntax checking
let g:airline#extensions#syntastic#enabled = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" don't forget to install with 'npm install jsxhint -g'
let g:syntastic_javscript_checkers = ['jsxhint']

" For vimdiff
set diffopt=filler
" set diffopt+=iwhite

" For ctrlp plugin to ignore files
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*

" Diff changes for opened file
if !exists(":DiffOrig")
    command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
          \ | wincmd p | diffthis
endif

" VSplit open pane to the right
set splitright

" Split open pane below
set splitbelow

" Remove trailing whitespacing before saving
autocmd BufWritePre *.rb :%s/\s\+$//e
autocmd BufWritePre *.js :%s/\s\+$//e
autocmd BufWritePre *.erb :%s/\s\+$//e

" Make the current window big, but leave others context
" set winwidth=84
" We have to have a winheight bigger than we want to set winminheight. But if
" we set winheight to be huge before winminheight, the winminheight set will
" fail.
" set winheight=5
" set winminheight=5
" set winheight=999

" Switch between the last two files
nnoremap <leader><leader> <c-^>

" Vimux should not open new panes
let g:VimuxUseNearestPane = 1

" HTML Indentation config
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style = "inc"

" Generate tags for Ruby projects with Bundler support.
" Generates for all  Gemfile gems.
map rt :execute "!bundle list --paths=true \| xargs ctags --extra=+f --exclude=.git --exclude=log -R *"<CR>

" Set highlight for
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
hi NonText ctermfg=7 guifg=gray
hi SpecialKey ctermfg=7 guifg=gray

" Don't display buffer line inside command bar, 'airline' will show it.
let g:bufferline_echo=0
let g:airline_enable_tagbar=1
let g:airline_enable_syntastic=1

" TagBar
let g:tagbar_autofocus = 1
nnoremap <silent> <F8> :TagbarToggle<CR>

" Don't allow gitgutter to update in realtime.
let g:gitgutter_realtime = 0

" Deleting buffers in CtrlP, with a plugin
call ctrlp_bdelete#init()

nnoremap <leader>1 :NERDTreeToggle<CR>
nnoremap <leader>! :NERDTreeFind<CR>

" position cursor between braces
imap <C-i> <CR><Esc>O

let g:indent_guides_guide_size = 1
let g:ycm_auto_trigger = 0
