set nocompatible
filetype off
filetype plugin indent off

" set the runtime path to include Vundle and initialize

call plug#begin('~/.vim/plugged')
Plug 'ctrlpvim/ctrlp.vim'
Plug 'Townk/vim-autoclose'
Plug 'scrooloose/nerdtree'
" Plug 'scrooloose/syntastic'
Plug 'dense-analysis/ale'
Plug 'godlygeek/tabular'
Plug 'majutsushi/tagbar'
Plug 'tomtom/tcomment_vim'
" Plug 'bling/vim-airline'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-tbone'
Plug 'airblade/vim-gitgutter'
Plug 'gregsexton/gitv'
Plug 'jelera/vim-javascript-syntax'
Plug 'tpope/vim-rails'
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-surround'
Plug 'kana/vim-textobj-user'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'd11wtq/ctrlp_bdelete.vim'
Plug 'justinmk/vim-gtfo'
Plug 'benmills/vimux'
Plug 'pangloss/vim-javascript'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'terryma/vim-multiple-cursors'
Plug 'mtth/scratch.vim'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'mattn/emmet-vim'
Plug 'schickling/vim-bufonly'
Plug 'janko-m/vim-test'
Plug 'embear/vim-localvimrc'
Plug 'mxw/vim-jsx'
Plug 'plasticboy/vim-markdown'
Plug 'elzr/vim-json'
" Plug 'ngmy/vim-rubocop'
Plug 'tpope/vim-unimpaired'
" Plug 'drn/zoomwin-vim'
Plug 'epeli/slimux'
Plug 'leafgarland/typescript-vim'
Plug 'junegunn/vim-easy-align'
Plug 'vim-scripts/indentpython.vim'
Plug 'nvie/vim-flake8' " python PEP 9 checking
Plug 'ycm-core/YouCompleteMe'
Plug 'mileszs/ack.vim'
"Plug 'stephpy/vim-yaml'
Plug 'pedrohdz/vim-yaml-folds'
" Plug 'hashivim/vim-terraform'
call plug#end()

filetype plugin indent on

" set t_Co=256
" set background=dark
" set colorcolumn=100

" colorscheme lucius


let g:NERDTreeNodeDelimiter = "\u00a0"

let python_highlight_all=1
syntax off

" set foldmethod=syntax

" enable matchit.vim for rubytext-block
runtime macros/matchit.vim

set nowrap "disable wrapping
set hidden "you can change buffers without saving
set expandtab
set tabstop=2
set shiftwidth=2
set bs=2
set number "show numbers
set showcmd "show partial command you are typing
set smarttab
set autoindent
set foldlevelstart=20

" local local .vimrc files (settings per project)
set exrc
set secure

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" put all vim's temporary file out of current dir
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" set the leader key
let mapleader = ","

let g:terraform_fmt_on_save = 1

" Keymaps
nnoremap <c-c> <ESC> " alternative ESCAPE
inoremap jj <ESC>
nmap <F3> :cn<CR> " find next occurance after vimgrep
nmap <F4> :cp<CR> " find previous occurance after vimgrep

" let test#strategy = "basic"
" vim-test bindings
nmap <leader>X :TestNearest<CR>
nmap <leader>x :TestFile<CR>
nmap <leader>xs :TestSuite<CR>
nmap <leader>xl :TestLast<CR>
"nmap <silent> <leader>g :TestVisit<CR>

" let test#strategy = {
"   \ 'nearest': 'vimux',
"   \ 'file':    'vimux',
"   \ 'suite':   'basic',
" \}
let test#strategy = {
  \ 'nearest': 'vimterminal',
  \ 'file':    'vimterminal',
  \ 'suite':   'vimterminal',
\}


" let g:no_turbux_mappings = 1
" map <leader>x <Plug>SendTestToTmux
" map <leader>X <Plug>SendFocusedTestToTmux

" Turbux should use drb by default
" let g:turbux_command_prefix = 'bundle exec'
" let g:turbux_command_cucumber  = 'cucumber --drb'
" let g:turbux_command_rspec     = 'rspec -f d'
" let g:turbux_command_test_unit = 'ruby -Itest'
"
 "change default cursor keys to work on visual not actual lines

nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

if has("gui_running")
  " If the current buffer has never been saved, it will have no name,
  " call the file browser to save it, otherwise just save it.
  :map <silent> <C-S> :if expand("%") == ""<CR>:browse confirm w<CR>:else<CR>:confirm w<CR>:endif<CR>
endif

" Toggle invisible characters
nmap <silent> <Leader>l :set list!<CR>

" CtrlP in open buffer mode
map <silent> <Leader>t :CtrlPBuffer<CR>
map <silent> <Leader>m :CtrlPMRU<CR>

" Send to REPL
map <Leader>s :SlimuxREPLSendLine<CR>
vmap <Leader>s :SlimuxREPLSendSelection<CR>

" Status Line
set statusline=%F%m%r%h%w[%L][%{&ff}]%y[%p%%][%04l,%04v]

" statusline support for syntactic plugin
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

" ALE
" let g:ale_fixers = {'ruby': ['rubocop']}
let g:ale_ruby_rubocop_executable = 'reevoocop'
let g:ale_fixers = { 'terraform': ['terraform lint'], 'ruby': 'rubocop' }

" Statusline always visible
set laststatus=2

" Close NERDTree when opening a file
let g:NERDTreeQuitOnOpen = 1

" Size of window
let g:NERDTreeWinSize = 40

" Enable syntastic syntax checking
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" For vimdiff
set diffopt=filler
" set diffopt+=iwhite

set wildignore+=*/.git/*,*/.hg/*,*/.svn/*

" ctrlp - use directory of current window
let g:ctrlp_working_path_mode = 'ra'

" Diff changes for opened file
if !exists(":DiffOrig")
    command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
          \ | wincmd p | diffthis
endif

" VSplit open pane to the right
set splitright

" Split open pane below
set splitbelow

" Remove trailing whitespace from code files on save
function! StripTrailingWhitespace()
  " store current cursor location
  silent exe "normal ma<CR>"
  " store the current search value
  let saved_search = @/
  " delete the whitespace (e means don't warn if pattern not found)
  %s/\s\+$//e
  " restore old cursor location
  silent exe "normal `a<CR>"
  " restore the search value
  let @/ = saved_search
endfunction


if has('autocmd')
  augroup autocommandbots
    autocmd!
    " Remove trailing whitespace from various files
    autocmd BufWritePre,FileWritePre *.html,*.rb,*.php,*.xml,*.erb,*.rhtml call StripTrailingWhitespace()
    autocmd Filetype coffee,ruby,yaml,yml,rake,rb,ru,javascript,terraform setlocal ts=2 sw=2 expandtab
    autocmd BufNewFile,BufRead {*.rake,Podfile,Gemfile,Guardfile,Capfile,Rakefile,Thorfile,config.ru} set ft=ruby
    autocmd BufNewFile,BufRead *.json set ft=javascript
    autocmd BufNewFile,BufRead *.prawn set ft=ruby
    autocmd BufNewFile,BufRead *.go set ft=go
    au! BufNewFile,BufReadPost *.{yaml,yml,raml,Gemfile.locak} set filetype=yaml foldmethod=indent
    autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
  augroup END
endif

" Switch between the last two files
nnoremap <leader><leader> <c-^>

" Vimux should not open new panes
let g:VimuxUseNearestPane = 1

" HTML Indentation config
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style = "inc"

" Generate tags for Ruby projects with Bundler support.
" Generates for all  Gemfile gems.
map rt :execute "!bundle list --paths=true \| xargs ctags --extra=+f --exclude=.git --exclude=log -R *"<CR>

" Set highlight for
"set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
"hi NonText ctermfg=7 guifg=gray
"hi SpecialKey ctermfg=7 guifg=gray

" Don't display buffer line inside command bar, 'airline' will show it.
let g:bufferline_echo=0

" airline
" let g:airline_powerline_fonts = 1


if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

" TagBar
let g:tagbar_autofocus = 1
nnoremap <silent><leader>2 :TagbarToggle<CR>

" Don't allow gitgutter to update in realtime.
let g:gitgutter_realtime = 0

" Deleting buffers in CtrlP, with a plugin
call ctrlp_bdelete#init()

nnoremap <leader>1 :NERDTreeToggle<CR>
nnoremap <leader>! :NERDTreeFind<CR>

let g:indent_guides_guide_size = 1
let g:ycm_auto_trigger = 0

" use silver search for ack.vim
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" Search with ack.vim
nnoremap K :Ack! "\b<C-R><C-W>\b"<CR>

nnoremap <c-w>O :only<CR>

" Ruby options
let g:ruby_indent_access_modifier_style = 'indent'

" Project specific settings
if filereadable('.vimrc.local')
  source .vimrc.local
endif

" scratch.vim settings
let g:scratch_insert_autohide = 0

" fugitive: checkout modified file with 'U'
au FileType gitcommit nmap <buffer> U :Git checkout -- <c-r><c-g><cr>

let g:notes_directories = ['~/Copy/Notes']

" ultisnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" NERDTree : make it same as CtrlP
let NERDTreeMapOpenSplit='<c-x>'
let NERDTreeMapOpenVSplit='<c-v>'

nnoremap <leader>bw :w!<CR>

" Persist localvimrc selections
let g:localvimrc_persistent=1

" Enable jsx support in .js files
let g:jsx_ext_required = 0

" don't forget to install with
"   'npm install -g eslint'
"   'npm install -g babel-eslint'
"   'npm install -g eslint-plugin-react'
let g:syntastic_javascript_checkers = ['eslint']

" ensure file watchers fire on save
set backupcopy=yes

" Vimux
nnoremap <leader>vl :VimuxRunCommand(getline("."))<CR>

" credit: http://stackoverflow.com/a/6271254
function! s:get_visual_selection()
  let [lnum1, col1] = getpos("'<")[1:2]
  let [lnum2, col2] = getpos("'>")[1:2]
  let lines = getline(lnum1, lnum2)
  let lines[-1] = lines[-1][: col2 - (&selection == 'inclusive' ? 1 : 2)]
  let lines[0] = lines[0][col1 - 1:]
  return join(lines, "\n")
endfunction

" python START
au BufNewFile,BufRead *.py
    \ set tabstop=4
    \ set softtabstop=4
    \ set shiftwidth=4
    \ set textwidth=79
    \ set expandtab
    \ set autoindent
    \ set fileformat=unix

au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree

" python END

set encoding=utf8

" set rnu

nnoremap <Leader>ve :split $MYVIMRC<cr>
nnoremap <Leader>vs :source $MYVIMRC<cr>

" regenerate ctags
nnoremap <leader>rt :silent :execute '!ctags -R -f tags --languages=ruby --exclude=.git --exclude=.terraform --exclude=log --exclude=tmp . $(bundle list --paths)'<CR><C-l>


